# OCEIF Node Installer for Windows — v24.0
# Usage: iwr -useb https://install.oceif.com/install.ps1 | iex
# Or save and run: powershell -ExecutionPolicy Bypass -File install.ps1
#
# Requires: PowerShell 5+ (Windows 10/11), Run as Administrator for service install
#Requires -Version 5

$ErrorActionPreference = "Stop"

$REPO      = "TuyenPKT/blockchain-rust"
$BINARY    = "blockchain-rust.exe"
$SERVICE   = "oceif-node"
$NETWORK   = "testnet"
$PEER      = "seed.testnet.oceif.com:8333"
$WEB_PORT  = 8082
$INSTALL_DIR = "$env:ProgramFiles\OCEIF"
$DATA_DIR    = "$env:ProgramData\OCEIF"
$CONFIG_DIR  = "$env:USERPROFILE\.pkt"

Write-Host "[install] OCEIF Node Installer — Windows" -ForegroundColor Cyan
Write-Host "[install] Network: $NETWORK  Peer: $PEER"

# ── Detect arch ───────────────────────────────────────────────────────────────
$arch = (Get-WmiObject Win32_OperatingSystem).OSArchitecture
if ($arch -match "64") {
    $TARGET = "x86_64-pc-windows-msvc"
} else {
    Write-Error "Unsupported architecture: $arch"
    exit 1
}

# ── Fetch latest release ──────────────────────────────────────────────────────
Write-Host "[install] Fetching latest release..."
$releaseUrl = "https://api.github.com/repos/$REPO/releases/latest"
$release = Invoke-RestMethod -Uri $releaseUrl -Headers @{ "User-Agent" = "oceif-installer" }
$VERSION = $release.tag_name
Write-Host "[install] Latest version: $VERSION"

$ARCHIVE = "blockchain-rust-$TARGET.zip"
$downloadUrl = "https://github.com/$REPO/releases/download/$VERSION/$ARCHIVE"

# ── Download & extract ────────────────────────────────────────────────────────
$TMP = [System.IO.Path]::GetTempPath() + [System.Guid]::NewGuid().ToString()
New-Item -ItemType Directory -Path $TMP | Out-Null

Write-Host "[install] Downloading $downloadUrl ..."
Invoke-WebRequest -Uri $downloadUrl -OutFile "$TMP\$ARCHIVE" -UseBasicParsing
Expand-Archive -Path "$TMP\$ARCHIVE" -DestinationPath $TMP -Force

# ── Install binary ────────────────────────────────────────────────────────────
$isAdmin = ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)

if ($isAdmin) {
    if (-not (Test-Path $INSTALL_DIR)) { New-Item -ItemType Directory -Path $INSTALL_DIR | Out-Null }
    Copy-Item "$TMP\$BINARY" "$INSTALL_DIR\$BINARY" -Force

    # Add to PATH if not already there
    $machinePath = [System.Environment]::GetEnvironmentVariable("PATH", "Machine")
    if ($machinePath -notlike "*$INSTALL_DIR*") {
        [System.Environment]::SetEnvironmentVariable("PATH", "$machinePath;$INSTALL_DIR", "Machine")
        Write-Host "[install] Added $INSTALL_DIR to system PATH"
    }
} else {
    $localBin = "$env:USERPROFILE\.local\bin"
    if (-not (Test-Path $localBin)) { New-Item -ItemType Directory -Path $localBin | Out-Null }
    Copy-Item "$TMP\$BINARY" "$localBin\$BINARY" -Force
    $INSTALL_DIR = $localBin
    Write-Host "[install] Not admin — installed to $localBin"
    Write-Host "[install] Add $localBin to your PATH manually if needed"
}

# ── Create data dir & config ──────────────────────────────────────────────────
if (-not (Test-Path $DATA_DIR))   { New-Item -ItemType Directory -Path $DATA_DIR   | Out-Null }
if (-not (Test-Path $CONFIG_DIR)) { New-Item -ItemType Directory -Path $CONFIG_DIR | Out-Null }

$configFile = "$CONFIG_DIR\config.toml"
if (-not (Test-Path $configFile)) {
    @"
# OCEIF Node config — generated by install.ps1
network  = "$NETWORK"
peer     = "$PEER"
web_port = $WEB_PORT
data_dir = "$DATA_DIR"
"@ | Set-Content -Path $configFile -Encoding UTF8
    Write-Host "[install] Config written to $configFile"
}

# ── Windows Service (admin only) ──────────────────────────────────────────────
if ($isAdmin) {
    $svcBinary = "$INSTALL_DIR\$BINARY"
    $svcArgs   = "fullnode $WEB_PORT $PEER"

    if (Get-Service -Name $SERVICE -ErrorAction SilentlyContinue) {
        Write-Host "[install] Stopping existing service..."
        Stop-Service -Name $SERVICE -Force
        sc.exe delete $SERVICE | Out-Null
        Start-Sleep -Seconds 2
    }

    Write-Host "[install] Creating Windows service: $SERVICE"
    New-Service -Name $SERVICE `
        -BinaryPathName "`"$svcBinary`" $svcArgs" `
        -DisplayName "OCEIF Node ($NETWORK)" `
        -Description "OCEIF blockchain node — $NETWORK" `
        -StartupType Automatic

    Start-Service -Name $SERVICE
    Write-Host "[install] Service started: $SERVICE"
    Write-Host "[install] Manage with: Get-Service $SERVICE | Start-Service / Stop-Service"
} else {
    Write-Host "[install] Skipping service install (not admin)"
    Write-Host "[install] To run manually:"
    Write-Host "    $INSTALL_DIR\$BINARY fullnode $WEB_PORT $PEER"
}

# ── Cleanup ───────────────────────────────────────────────────────────────────
Remove-Item -Recurse -Force $TMP

# ── Done ──────────────────────────────────────────────────────────────────────
Write-Host ""
Write-Host "╔══════════════════════════════════════════════════════╗" -ForegroundColor Green
Write-Host "║  OCEIF Node installed successfully!                  ║" -ForegroundColor Green
Write-Host "╟──────────────────────────────────────────────────────╢" -ForegroundColor Green
Write-Host "║  Network : $NETWORK"
Write-Host "║  Peer    : $PEER"
Write-Host "║  Web UI  : http://localhost:$WEB_PORT"
Write-Host "║  Config  : $configFile"
Write-Host "╟──────────────────────────────────────────────────────╢" -ForegroundColor Green
Write-Host "║  Check sync:"
Write-Host "║    Invoke-RestMethod http://localhost:$WEB_PORT/api/testnet/sync-status"
Write-Host "╚══════════════════════════════════════════════════════╝" -ForegroundColor Green
