#!/usr/bin/env sh
# OCEIF Node Installer — v24.0
# Usage: curl -sSL https://install.oceif.com | sh
# Or:    curl -sSL https://install.oceif.com | sh -s -- --mainnet
#
# Supported: Linux x86_64, Linux ARM64, macOS x86_64, macOS ARM64
set -e

REPO="TuyenPKT/blockchain-rust"
BINARY="blockchain-rust"
SERVICE="oceif-node"
NETWORK="testnet"
PEER="seed.testnet.oceif.com:8333"
WEB_PORT="8082"
INSTALL_DIR="/usr/local/bin"
DATA_DIR="/var/lib/oceif"
USER="oceif"

# ── Detect OS & arch ──────────────────────────────────────────────────────────
OS="$(uname -s)"
ARCH="$(uname -m)"

case "$OS" in
  Linux)
    case "$ARCH" in
      x86_64)  TARGET="x86_64-unknown-linux-gnu" ;;
      aarch64) TARGET="aarch64-unknown-linux-gnu" ;;
      armv7l)  TARGET="armv7-unknown-linux-gnueabihf" ;;
      *) echo "Unsupported arch: $ARCH"; exit 1 ;;
    esac
    ;;
  Darwin)
    TARGET="universal-apple-darwin"
    ;;
  *)
    echo "Unsupported OS: $OS. Download manually from https://github.com/$REPO/releases"
    exit 1
    ;;
esac

echo "[install] OS=$OS ARCH=$ARCH TARGET=$TARGET"

# ── Check dependencies ────────────────────────────────────────────────────────
need_cmd() { command -v "$1" >/dev/null 2>&1 || { echo "Required: $1"; exit 1; }; }
need_cmd curl
need_cmd tar

# ── Download latest release ───────────────────────────────────────────────────
LATEST=$(curl -sSL "https://api.github.com/repos/$REPO/releases/latest" \
  | grep '"tag_name"' | head -1 | sed 's/.*"tag_name": *"\(.*\)".*/\1/')

if [ -z "$LATEST" ]; then
  echo "[install] Could not fetch latest version. Check https://github.com/$REPO/releases"
  exit 1
fi

echo "[install] Latest version: $LATEST"

ARCHIVE="${BINARY}-${TARGET}.tar.gz"
URL="https://github.com/$REPO/releases/download/$LATEST/$ARCHIVE"

TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT

echo "[install] Downloading $URL ..."
curl -sSL "$URL" -o "$TMP/$ARCHIVE"
tar -xzf "$TMP/$ARCHIVE" -C "$TMP"

# ── Install binary ────────────────────────────────────────────────────────────
if [ "$(id -u)" -eq 0 ]; then
  install -m 755 "$TMP/$BINARY" "$INSTALL_DIR/$BINARY"
  echo "[install] Binary installed to $INSTALL_DIR/$BINARY"
else
  echo "[install] Not root — installing to ~/.local/bin"
  mkdir -p "$HOME/.local/bin"
  install -m 755 "$TMP/$BINARY" "$HOME/.local/bin/$BINARY"
  INSTALL_DIR="$HOME/.local/bin"
  echo "[install] Make sure $HOME/.local/bin is in your PATH"
fi

# ── Create data dir & config ──────────────────────────────────────────────────
mkdir -p "$DATA_DIR"

CONFIG_DIR="$HOME/.pkt"
mkdir -p "$CONFIG_DIR"

if [ ! -f "$CONFIG_DIR/config.toml" ]; then
  cat > "$CONFIG_DIR/config.toml" << TOML
# OCEIF Node config — generated by install.sh
network  = "$NETWORK"
peer     = "$PEER"
web_port = $WEB_PORT
data_dir = "$DATA_DIR"
TOML
  echo "[install] Config written to $CONFIG_DIR/config.toml"
fi

# ── systemd (Linux root) ──────────────────────────────────────────────────────
if [ "$OS" = "Linux" ] && [ "$(id -u)" -eq 0 ] && command -v systemctl >/dev/null 2>&1; then
  # Create user if not exists
  if ! id "$USER" >/dev/null 2>&1; then
    useradd --system --no-create-home --shell /usr/sbin/nologin "$USER"
    echo "[install] Created system user: $USER"
  fi
  chown -R "$USER:$USER" "$DATA_DIR"

  cat > "/etc/systemd/system/$SERVICE.service" << SERVICE
[Unit]
Description=OCEIF Node ($NETWORK)
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=$USER
WorkingDirectory=$DATA_DIR
ExecStart=$INSTALL_DIR/$BINARY fullnode $WEB_PORT $PEER
Restart=on-failure
RestartSec=10s
Environment=RUST_LOG=info
LimitNOFILE=65536
ProtectSystem=strict
ReadWritePaths=$DATA_DIR /home/$USER
NoNewPrivileges=true

[Install]
WantedBy=multi-user.target
SERVICE

  systemctl daemon-reload
  systemctl enable --now "$SERVICE"
  echo "[install] Service enabled: $SERVICE"
  echo "[install] Status: systemctl status $SERVICE"

# ── launchd (macOS) ───────────────────────────────────────────────────────────
elif [ "$OS" = "Darwin" ]; then
  PLIST="$HOME/Library/LaunchAgents/com.oceif.node.plist"
  cat > "$PLIST" << PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>             <string>com.oceif.node</string>
  <key>ProgramArguments</key>
  <array>
    <string>$INSTALL_DIR/$BINARY</string>
    <string>fullnode</string>
    <string>$WEB_PORT</string>
    <string>$PEER</string>
  </array>
  <key>RunAtLoad</key>         <true/>
  <key>KeepAlive</key>         <true/>
  <key>StandardOutPath</key>   <string>$HOME/.pkt/node.log</string>
  <key>StandardErrorPath</key> <string>$HOME/.pkt/node.err</string>
  <key>EnvironmentVariables</key>
  <dict>
    <key>RUST_LOG</key> <string>info</string>
  </dict>
</dict>
</plist>
PLIST
  launchctl load "$PLIST"
  echo "[install] launchd agent loaded: com.oceif.node"
fi

# ── Done ──────────────────────────────────────────────────────────────────────
echo ""
echo "╔══════════════════════════════════════════════════════╗"
echo "║  OCEIF Node installed successfully!                  ║"
echo "╟──────────────────────────────────────────────────────╢"
echo "║  Network : $NETWORK"
echo "║  Peer    : $PEER"
echo "║  Web UI  : http://localhost:$WEB_PORT"
echo "║  Config  : $CONFIG_DIR/config.toml"
echo "╟──────────────────────────────────────────────────────╢"
echo "║  Check sync:                                         ║"
echo "║    curl http://localhost:$WEB_PORT/api/testnet/sync-status"
echo "╚══════════════════════════════════════════════════════╝"
