#![allow(dead_code)]
//! v11.9 — Deploy Config
//! Docker/systemd config generator + frontend embed + `cargo run -- deploy init`

use serde::{Deserialize, Serialize};

// ── Embedded frontend (compile-time) ──────────────────────────────────────────
pub const FRONTEND_HTML: &[u8] = include_bytes!("../index.html");

// ── Config struct ─────────────────────────────────────────────────────────────

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct DeployConfig {
    pub app_name:     String,
    pub network:      String,  // regtest | testnet | mainnet
    pub api_port:     u16,
    pub p2p_port:     u16,
    pub pktscan_port: u16,
    pub data_dir:     String,
    pub log_level:    String,  // error | warn | info | debug
    pub rust_log:     String,
}

impl Default for DeployConfig {
    fn default() -> Self {
        DeployConfig {
            app_name:     "pkt-node".to_string(),
            network:      "testnet".to_string(),
            api_port:     3000,
            p2p_port:     8333,
            pktscan_port: 8080,
            data_dir:     "/var/lib/pkt".to_string(),
            log_level:    "info".to_string(),
            rust_log:     "info,blockchain_rust=debug".to_string(),
        }
    }
}

impl DeployConfig {
    pub fn new() -> Self { Self::default() }

    pub fn for_network(network: &str) -> Self {
        let mut cfg = Self::default();
        cfg.network = network.to_string();
        match network {
            "regtest" => { cfg.p2p_port = 18444; cfg.api_port = 13000; cfg.pktscan_port = 13080; }
            "mainnet" => { cfg.p2p_port = 8333;  cfg.api_port = 3000;  cfg.pktscan_port = 8080; }
            _ => {}  // testnet defaults
        }
        cfg
    }

    // ── Generators ────────────────────────────────────────────────────────────

    pub fn dockerfile(&self) -> String {
        format!(r#"# Auto-generated by blockchain-rust v11.9
FROM rust:1.75-slim-bookworm AS builder
WORKDIR /app
COPY . .
RUN apt-get update && apt-get install -y libclang-dev libssl-dev pkg-config && rm -rf /var/lib/apt/lists/*
RUN cargo build --release

FROM debian:bookworm-slim
RUN apt-get update && apt-get install -y libssl3 ca-certificates && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY --from=builder /app/target/release/blockchain-rust /usr/local/bin/pkt-node
COPY --from=builder /app/index.html /app/index.html

ENV PKT_NETWORK={network}
ENV PKT_DATA_DIR={data_dir}
ENV RUST_LOG={rust_log}

EXPOSE {p2p_port} {api_port} {pktscan_port}

ENTRYPOINT ["pkt-node"]
CMD ["pktscan", "{pktscan_port}"]
"#,
            network     = self.network,
            data_dir    = self.data_dir,
            rust_log    = self.rust_log,
            p2p_port    = self.p2p_port,
            api_port    = self.api_port,
            pktscan_port = self.pktscan_port,
        )
    }

    pub fn docker_compose(&self) -> String {
        format!(r#"# Auto-generated by blockchain-rust v11.9
version: "3.9"

services:
  {app}:
    build: .
    container_name: {app}
    restart: unless-stopped
    ports:
      - "{p2p}:{p2p}"
      - "{api}:{api}"
      - "{scan}:{scan}"
    volumes:
      - pkt_data:{data_dir}
    environment:
      - PKT_NETWORK={network}
      - PKT_DATA_DIR={data_dir}
      - RUST_LOG={rust_log}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:{scan}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  pkt_data:
    driver: local
"#,
            app      = self.app_name,
            p2p      = self.p2p_port,
            api      = self.api_port,
            scan     = self.pktscan_port,
            data_dir = self.data_dir,
            network  = self.network,
            rust_log = self.rust_log,
        )
    }

    pub fn systemd_service(&self) -> String {
        format!(r#"# Auto-generated by blockchain-rust v11.9
# Install: sudo cp {app}.service /etc/systemd/system/
#          sudo systemctl daemon-reload && sudo systemctl enable --now {app}
[Unit]
Description=PKT Node ({network})
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=pkt
Group=pkt
WorkingDirectory=/opt/pkt
ExecStart=/usr/local/bin/pkt-node pktscan {pktscan_port}
Restart=on-failure
RestartSec=5s
Environment=PKT_NETWORK={network}
Environment=PKT_DATA_DIR={data_dir}
Environment=RUST_LOG={rust_log}
LimitNOFILE=65536
ProtectSystem=strict
ReadWritePaths={data_dir}
NoNewPrivileges=true

[Install]
WantedBy=multi-user.target
"#,
            app          = self.app_name,
            network      = self.network,
            pktscan_port = self.pktscan_port,
            data_dir     = self.data_dir,
            rust_log     = self.rust_log,
        )
    }

    pub fn env_file(&self) -> String {
        format!(r#"# Auto-generated by blockchain-rust v11.9
PKT_NETWORK={network}
PKT_DATA_DIR={data_dir}
PKT_API_PORT={api_port}
PKT_P2P_PORT={p2p_port}
PKT_PKTSCAN_PORT={pktscan_port}
RUST_LOG={rust_log}
"#,
            network      = self.network,
            data_dir     = self.data_dir,
            api_port     = self.api_port,
            p2p_port     = self.p2p_port,
            pktscan_port = self.pktscan_port,
            rust_log     = self.rust_log,
        )
    }

    pub fn nginx_conf(&self) -> String {
        format!(r#"# Auto-generated by blockchain-rust v11.9
# Install: sudo cp pkt.conf /etc/nginx/sites-available/ && sudo ln -s ../sites-available/pkt.conf /etc/nginx/sites-enabled/
server {{
    listen 80;
    server_name _;

    # Block explorer frontend + API
    location / {{
        proxy_pass http://127.0.0.1:{pktscan_port};
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }}

    # WebSocket upgrade
    location /ws {{
        proxy_pass http://127.0.0.1:{pktscan_port};
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }}
}}
"#,
            pktscan_port = self.pktscan_port,
        )
    }

    /// Serialize config to JSON
    pub fn to_json(&self) -> String {
        serde_json::to_string_pretty(self).unwrap_or_default()
    }

    /// Deserialize from JSON
    pub fn from_json(s: &str) -> Result<Self, String> {
        serde_json::from_str(s).map_err(|e| e.to_string())
    }
}

// ── CLI ───────────────────────────────────────────────────────────────────────

fn die(msg: &str) -> ! {
    eprintln!("error: {}", msg);
    std::process::exit(1);
}

pub fn cmd_deploy(args: &[String]) {
    let sub = args.get(2).map(|s| s.as_str()).unwrap_or("help");
    let net = args.get(3).map(|s| s.as_str()).unwrap_or("testnet");
    let cfg = DeployConfig::for_network(net);

    match sub {
        "init" => {
            // Write all config files to current directory
            write_file("Dockerfile",         &cfg.dockerfile());
            write_file("docker-compose.yml", &cfg.docker_compose());
            write_file(".env",               &cfg.env_file());
            write_file("pkt.service",        &cfg.systemd_service());
            write_file("nginx-pkt.conf",     &cfg.nginx_conf());
            write_file("deploy-config.json", &cfg.to_json());
            // Write embedded frontend
            write_bytes("index.html", FRONTEND_HTML);

            println!("✓ Deploy config generated for network: {}", net);
            println!("  Dockerfile          ← docker build + multi-stage");
            println!("  docker-compose.yml  ← ports {}/{}/{}", cfg.p2p_port, cfg.api_port, cfg.pktscan_port);
            println!("  .env                ← environment variables");
            println!("  pkt.service         ← systemd unit (copy to /etc/systemd/system/)");
            println!("  nginx-pkt.conf      ← reverse proxy config");
            println!("  deploy-config.json  ← full config JSON");
            println!("  index.html          ← PKTScan frontend");
            println!();
            println!("  Next steps:");
            println!("    docker compose up -d          # Docker deploy");
            println!("    sudo systemctl start pkt-node # systemd deploy");
        }
        "dockerfile" => {
            print!("{}", cfg.dockerfile());
        }
        "compose" => {
            print!("{}", cfg.docker_compose());
        }
        "systemd" => {
            print!("{}", cfg.systemd_service());
        }
        "env" => {
            print!("{}", cfg.env_file());
        }
        "nginx" => {
            print!("{}", cfg.nginx_conf());
        }
        "frontend" => {
            println!("Frontend size: {} bytes", FRONTEND_HTML.len());
            println!("First 80 chars: {}", String::from_utf8_lossy(&FRONTEND_HTML[..80.min(FRONTEND_HTML.len())]));
        }
        "config" => {
            println!("{}", cfg.to_json());
        }
        _ => {
            println!("Usage: cargo run -- deploy <sub> [network]");
            println!("  init [net]      generate all config files (net: regtest|testnet|mainnet)");
            println!("  dockerfile      print Dockerfile");
            println!("  compose         print docker-compose.yml");
            println!("  systemd         print systemd service");
            println!("  env             print .env file");
            println!("  nginx           print nginx reverse proxy config");
            println!("  frontend        show embedded frontend info");
            println!("  config          print full deploy config as JSON");
        }
    }
}

fn write_file(name: &str, content: &str) {
    match std::fs::write(name, content) {
        Ok(_)  => println!("  wrote {}", name),
        Err(e) => eprintln!("  warn: could not write {}: {}", name, e),
    }
}

fn write_bytes(name: &str, content: &[u8]) {
    match std::fs::write(name, content) {
        Ok(_)  => println!("  wrote {}", name),
        Err(e) => eprintln!("  warn: could not write {}: {}", name, e),
    }
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    fn cfg() -> DeployConfig { DeployConfig::default() }

    // ── DeployConfig defaults ─────────────────────────────────────────────────

    #[test]
    fn test_default_network_is_testnet() {
        assert_eq!(cfg().network, "testnet");
    }

    #[test]
    fn test_default_ports() {
        let c = cfg();
        assert_eq!(c.api_port, 3000);
        assert_eq!(c.p2p_port, 8333);
        assert_eq!(c.pktscan_port, 8080);
    }

    #[test]
    fn test_for_network_regtest() {
        let c = DeployConfig::for_network("regtest");
        assert_eq!(c.network, "regtest");
        assert_eq!(c.p2p_port, 18444);
        assert_eq!(c.api_port, 13000);
    }

    #[test]
    fn test_for_network_mainnet() {
        let c = DeployConfig::for_network("mainnet");
        assert_eq!(c.network, "mainnet");
        assert_eq!(c.p2p_port, 8333);
    }

    #[test]
    fn test_for_network_testnet_defaults() {
        let c = DeployConfig::for_network("testnet");
        assert_eq!(c.pktscan_port, 8080);
    }

    // ── Dockerfile ────────────────────────────────────────────────────────────

    #[test]
    fn test_dockerfile_contains_from() {
        let d = cfg().dockerfile();
        assert!(d.contains("FROM rust:"));
    }

    #[test]
    fn test_dockerfile_exposes_ports() {
        let d = cfg().dockerfile();
        assert!(d.contains("EXPOSE"));
        assert!(d.contains("8333"));
        assert!(d.contains("8080"));
    }

    #[test]
    fn test_dockerfile_sets_network_env() {
        let d = cfg().dockerfile();
        assert!(d.contains("PKT_NETWORK=testnet"));
    }

    // ── docker-compose ────────────────────────────────────────────────────────

    #[test]
    fn test_compose_contains_services() {
        let c = cfg().docker_compose();
        assert!(c.contains("services:"));
        assert!(c.contains("pkt-node"));
    }

    #[test]
    fn test_compose_contains_volumes() {
        let c = cfg().docker_compose();
        assert!(c.contains("volumes:"));
        assert!(c.contains("pkt_data"));
    }

    #[test]
    fn test_compose_contains_healthcheck() {
        let c = cfg().docker_compose();
        assert!(c.contains("healthcheck:"));
        assert!(c.contains("/health"));
    }

    // ── systemd service ───────────────────────────────────────────────────────

    #[test]
    fn test_systemd_contains_unit_section() {
        let s = cfg().systemd_service();
        assert!(s.contains("[Unit]"));
        assert!(s.contains("[Service]"));
        assert!(s.contains("[Install]"));
    }

    #[test]
    fn test_systemd_restart_on_failure() {
        let s = cfg().systemd_service();
        assert!(s.contains("Restart=on-failure"));
    }

    #[test]
    fn test_systemd_no_new_privileges() {
        let s = cfg().systemd_service();
        assert!(s.contains("NoNewPrivileges=true"));
    }

    // ── .env file ─────────────────────────────────────────────────────────────

    #[test]
    fn test_env_file_has_all_keys() {
        let e = cfg().env_file();
        assert!(e.contains("PKT_NETWORK="));
        assert!(e.contains("PKT_DATA_DIR="));
        assert!(e.contains("PKT_API_PORT="));
        assert!(e.contains("PKT_P2P_PORT="));
        assert!(e.contains("PKT_PKTSCAN_PORT="));
        assert!(e.contains("RUST_LOG="));
    }

    // ── nginx ─────────────────────────────────────────────────────────────────

    #[test]
    fn test_nginx_conf_has_proxy_pass() {
        let n = cfg().nginx_conf();
        assert!(n.contains("proxy_pass"));
        assert!(n.contains("8080"));
    }

    #[test]
    fn test_nginx_conf_has_websocket_upgrade() {
        let n = cfg().nginx_conf();
        assert!(n.contains("Upgrade"));
        assert!(n.contains("/ws"));
    }

    // ── JSON roundtrip ────────────────────────────────────────────────────────

    #[test]
    fn test_json_roundtrip() {
        let c = cfg();
        let json = c.to_json();
        let c2 = DeployConfig::from_json(&json).unwrap();
        assert_eq!(c, c2);
    }

    #[test]
    fn test_json_invalid_returns_err() {
        let r = DeployConfig::from_json("not-json");
        assert!(r.is_err());
    }

    // ── Frontend embed ────────────────────────────────────────────────────────

    #[test]
    fn test_frontend_html_non_empty() {
        assert!(!FRONTEND_HTML.is_empty());
    }

    #[test]
    fn test_frontend_html_is_html() {
        let text = String::from_utf8_lossy(FRONTEND_HTML);
        assert!(text.contains("<!DOCTYPE html>") || text.contains("<html"));
    }
}
